language: python
python:
  - 3.8.1
install:
  - pip install -q pipenv
  - pipenv sync --dev
  - cp contrib/env-sample .env
script:
  - pipenv run flake8
  - pipenv run pytest --cov=pypro

after_success:
  - pipenv run codecov
